title = "Morgana"
author = "loghost#2690"
description = "The classic Morgana team comp. Ganyu/Mona/Venti/Diona"

version = "0.1.0"

characters = [
    "ganyu",
    "mona",
    "venti",
    "diona"
]

config = '''
# Morgana: Ganyu/Mona/Venti/Diona

# Rotation is as follows: Ganyu E Q, Venti E Q, Mona Q E, Diona E E, Venti E, Ganyu 3xCA

##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
#target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=ganyu;
energy+=every interval=200,300 amount=1;

# Ganyu E Q
actions+=sequence_strict target=ganyu exec=skill,burst;

# Venti E Q
actions+=sequence_strict target=venti exec=skill,burst if=.status.ganyuburst>0;

# Mona Q E
actions+=sequence_strict target=mona exec=burst,skill if=.status.ventiburst>0;

# Diona E E
actions+=sequence target=diona exec=skill,skill;

# Venti E
actions+=sequence_strict target=venti exec=skill;

# Ganyu 3xCA
actions+=sequence_strict target=ganyu exec=aim,aim,dash,aim,aim,dash,aim,aim,dash;
'''