title = "Pyro-Anemo Quickswap"
author = "loghost#2690"
description = "Bennett/Xiangling/Kazuha/Venti"

version = "0.1.0"

characters = [
    "bennett",
    "xiangling",
    "kaedeharakazuha",
    "venti"
]

config = '''
# Pyro-Anemo Quickswap: Bennett/Xiangling/Kazuha/Venti

# Rotation is as follows: Bennett Q E, Venti Q, Kazuha Q EP, Xiangling Q E, (Bennett E to Xiangling, Venti E, Kazuha EP to fill)

##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
#target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=bennett;
energy+=every interval=200,300 amount=1;

# Bennett Q E
actions+=sequence_strict target=bennett exec=burst,skill if=.status.btburst==0;

# Venti E Q
actions+=sequence_strict target=venti exec=skill,burst if=.status.btburst>0;

# Kazuha Q EP
actions+=sequence_strict target=kaedeharakazuha exec=burst,skill,high_plunge if=.status.btburst>0;

# Xiangling Q E
actions+=sequence_strict target=xiangling exec=burst,skill if=.status.btburst>0;

# Fill actions
actions+=sequence_strict target=bennett exec=skill if=.energy.xiangling<80 swap=xiangling;
actions+=sequence_strict target=venti exec=skill;
actions+=sequence_strict target=kaedeharakazuha exec=skill,high_plunge if=.energy.xiangling<80;
'''