#title, author and description are mandatory fields
title = "Sample action list"
author = "tsym"
description = "Hu Tao (Bennett+VV)"
tags = [
    "hutao",
    "vv"
]

# version is an optional field for authors to keep track
version = "0.1.0"
# characters should be array of character names (all lowercase); this is mandatory
characters = [
    "hutao",
    "xingqiu",
    "bennett",
    "sucrose"
]

# config is the action list, stored in multiline string
config = '''
##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=xingqiu;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
# From elijam assumptions: https://discord.com/channels/763583452762734592/851428030094114847/884832120650993805
energy+=every interval=200,300 amount=1;

# Hu tao frames are currently kind of screwy - need some manual dashes added
# actions+=sequence_strict target=hutao exec=attack,attack,charge,dash if=.status.xqburst>0&&.status.paramita>75;
# actions+=sequence_strict target=hutao exec=attack,burst if=.status.paramita<=75&&.status.paramita>0;
actions+=sequence_strict target=hutao exec=attack,charge,dash,dash,attack,charge,dash,dash,attack,charge,dash,attack,charge,dash,dash,attack,charge,dash,dash,attack,charge,dash,attack,charge,dash,dash,attack,burst if=.status.paramita>120 lock=540;
actions+=sequence_strict target=hutao exec=attack,charge,dash,dash,attack,charge,dash,dash,attack,charge,dash,attack,charge,dash,dash,attack,charge,jump,attack,charge,jump,attack,charge,jump,attack,charge,jump,attack,charge if=.status.paramita>120 lock=540;

# Test on other sequences
# actions+=sequence_strict target=hutao exec=attack,attack,charge,dash,dash,attack,attack,charge,dash,attack,attack,charge,dash,dash,attack,attack,charge,dash,attack,attack,charge,dash,dash,attack,attack,charge,dash,attack,attack,charge,dash,dash,attack,burst if=.status.paramita>120 lock=540;
# actions+=sequence_strict target=hutao exec=attack,attack,charge,dash,dash,attack,attack,charge,dash,attack,attack,charge,dash,dash,attack,attack,charge,dash,attack,attack,charge,dash,dash,attack,attack,charge,dash,attack,attack,charge,dash,dash if=.status.paramita>120 lock=540;

actions+=sequence_strict target=xingqiu exec=skill[orbital=1],burst[orbital=1];
actions+=sequence_strict target=bennett exec=burst,skill if=.status.xqburst>0&&.status.xqburst>720;
actions+=sequence_strict target=sucrose exec=attack,skill if=.element.pyro==1&&.status.btburst>600;

actions+=sequence_strict target=hutao exec=skill if=.status.btburst>0;

# actions+=sequence_strict target=hutao exec=attack,skill,attack,charge,dash,dash,attack,charge,dash,dash,attack,charge,dash,attack,charge,dash,dash,attack,charge,dash,dash,attack,charge,dash,attack,charge,dash,dash,attack,burst if=.status.btburst>0 lock=540;
# actions+=sequence_strict target=hutao exec=attack,skill,attack,charge,dash,dash,attack,charge,dash,dash,attack,charge,dash,attack,charge,dash,dash,attack,charge,dash,dash,attack,charge,dash,attack,charge,dash,dash,attack,charge,dash,attack,charge if=.status.btburst>0 lock=540;

actions+=sequence_strict target=bennett exec=attack,skill if=.status.xqburst>0;
actions+=sequence_strict target=bennett exec=skill if=.cd.xingqiu.burst>120||.energy.xingqiu<80;

actions+=attack target=xingqiu if=.status.xqburst>0;
actions+=attack target=hutao active=hutao;

'''