#title, author and description are mandatory fields
title = "Melt Ganyu"
author = "tsym"
description = "Melt Ganyu"

# version is an optional field for authors to keep track
version = "0.1.0"
# characters should be array of character names (all lowercase); this is mandatory
characters = [
    "ganyu",
    "zhongli",
    "xiangling",
    "bennett"
]

# config is the action list, stored in multiline string
config = '''
##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=bennett;

# HP particle simulation. Per srl:
# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy+=every interval=200,300 amount=1;

actions+=sequence_strict exec=skill target=bennett if=.element.pyro==0&&.element.cryo==0;

# Attacks are to create the shield right before swapping
actions+=sequence_strict exec=attack,attack,skill[hold_nosteele=1] target=zhongli if=.energy.xiangling>70&&.cd.bennett.burst<60;

actions+=sequence_strict exec=burst,skill target=bennett if=.cd.xiangling.skill<120&&.cd.xiangling.burst<120;
actions+=sequence_strict exec=burst target=bennett if=.cd.xiangling.skill<50&&.cd.xiangling.burst<50;

actions+=sequence_strict exec=burst,skill target=xiangling if=.status.xianglingguoba==0&&.status.btburst>0;

# Added lock to slow down shots to align with calcs
# Apparently you can only fit 6 CA in. Sim appears to do a lot better than that, so we artificially constrain it to 6 to be realistic
# Also need to lock her in place as well
actions+=sequence_strict exec=skill,aim,aim,dash,aim,dash,aim,aim,aim target=ganyu if=.status.xianglingburst>0 actionlock=800 lock=700;

actions+=sequence_strict exec=skill,attack target=bennett swap=xiangling if=.energy.xiangling<65;
actions+=skill target=bennett if=.energy.xiangling<75;

actions+=attack target=zhongli;
actions+=attack target=xiangling active=xiangling;

'''