#title, author and description are mandatory fields
title = "National (Fischl)"
author = "tsym"
description = "national team with fischl"

# version is an optional field for authors to keep track
version = "0.1.0"
# characters should be array of character names (all lowercase); this is mandatory
characters = [
    "xiangling",
    "xingqiu",
    "bennett",
    "fischl"
]

# config is the action list, stored in multiline string
config = '''
##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=bennett;


# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
# From elijam assumptions: https://discord.com/channels/763583452762734592/851428030094114847/884832120650993805
energy+=every interval=200,300 amount=1;

actions+=sequence_strict target=xingqiu exec=skill[orbital=1],burst,attack if=.cd.xiangling.burst<270&&.energy.xiangling>73;

actions+=sequence_strict target=bennett exec=burst,skill,attack if=.cd.xiangling.burst<120&&.energy.xiangling>73&&.status.xqburst>0;

actions+=sequence_strict target=xiangling exec=burst,attack,skill if=.status.btburst>0;
actions+=sequence_strict target=xiangling exec=burst if=.status.btburst>0;

actions+=sequence_strict exec=attack,attack,burst target=fischl;
actions+=sequence_strict exec=skill,attack target=fischl if=.status.fischloz==0;

# Funnelling - only used when XL burst is off as otherwise you steal vapes
actions+=sequence_strict target=bennett exec=attack,skill if=.status.xqburst>0&&.status.xianglingburst<240&&.energy.xiangling<71 swap=xiangling;
actions+=sequence_strict target=bennett exec=skill if=.status.xianglingburst<240&&.energy.xiangling<71 swap=xiangling;

actions+=attack target=xingqiu if=.status.xqburst>0&&.status.btburst>0;
actions+=attack target=xiangling active=xiangling;
actions+=attack target=bennett active=bennett;
actions+=attack target=xingqiu active=xingqiu;

'''