#title, author and description are mandatory fields
title = "Raiden Hypercarry"
author = "tsym"
description = "Raiden big damage"

# version is an optional field for authors to keep track
version = "0.1.0"
# characters should be array of character names (all lowercase); this is mandatory
characters = [
    "raidenshogun",
    "sara",
    "bennett",
    "kaedeharakazuha"
]

# config is the action list, stored in multiline string
config = '''
##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
# target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=raidenshogun;


# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy+=every interval=200,300 amount=1;

actions+=sequence_strict target=raidenshogun exec=attack,attack,attack,charge,attack,attack,attack,charge,attack,attack,charge,attack,charge if=.status.raidenburst>0;

# Need to hold at the start or otherwise Kazuha won't get an electro VV proc due to timing with Bennett Q
actions+=skill target=raidenshogun if=.status.raidenskill<360 lock=40;
# Refresh at end of burst rotation
actions+=skill target=raidenshogun if=.cd.raidenshogun.burst<600&&.status.btburst==0;

# Bennett burst goes after XQ burst for uptime alignment. Attack to proc swords
actions+=sequence_strict target=bennett exec=burst if=.cd.sara.burst<270;

actions+=sequence_strict target=kaedeharakazuha exec=skill,high_plunge,burst if=.status.btburst>0;

actions+=sequence_strict target=sara exec=burst[wave_attack_procs=111] if=.status.btburst>0;
actions+=sequence_strict target=sara exec=skill,aim if=.status.btburst>0&&.cd.sara.burst<300;

# Raiden must burst after all others. Requires an attack to allow Bennett buff to apply
actions+=sequence_strict target=raidenshogun exec=burst if=.status.btburst>0;

# Gap fill until next rotation
# actions+=sequence_strict target=kaedeharakazuha exec=skill,high_plunge;
actions+=sequence_strict target=bennett exec=skill if=.status.btburst==0;
actions+=sequence_strict target=sara exec=skill,aim;

actions+=attack target=bennett active=bennett;
actions+=attack target=sara active=sara;


'''