#title, author and description are mandatory fields
title = "Raiden Double Pyro"
author = "tsym"
description = "Raiden with double pyro and Fischl"

# version is an optional field for authors to keep track
version = "0.1.0"
# characters should be array of character names (all lowercase); this is mandatory
characters = [
    "raidenshogun",
    "xiangling",
    "bennett",
    "fischl"
]

# config is the action list, stored in multiline string
config = '''

##Default Enemy
target+="dummy" lvl=100 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;

##Actions List
active+=bennett;


# it adds 1 particle randomly, uniformly distributed between 200 to 300 frames after the last time an energy drops
# so in the case above, it adds on avg one particle every 250 frames in effect
# so over 90s of combat that's 90 * 60 / 250 = 21.6 on avg
energy+=every interval=200,300 amount=1;

actions+=sequence_strict target=raidenshogun exec=attack,attack,attack,attack,attack,attack,attack,attack,dash,attack,attack,attack,attack,dash,attack,attack,attack,charge if=.status.raidenburst>300;

actions+=skill target=raidenshogun if=.status.raidenskill<300;

actions+=sequence_strict target=bennett exec=burst,skill if=.energy.xiangling>75&&.cd.xiangling.burst<120&&.cd.xiangling.skill<240;

actions+=sequence_strict target=xiangling exec=burst,skill if=.status.btburst>0;

actions+=sequence_strict target=fischl exec=attack,attack,burst if=.status.btburst>0;
actions+=skill target=fischl if=.status.fischloz==0;

actions+=burst target=raidenshogun if=.status.xianglingburst>0&&.status.btburst>0;

# Feeding
actions+=skill target=bennett if=.energy.xiangling<77&&.status.btburst==0 swap=xiangling;

actions+=attack target=xiangling active=xiangling;
actions+=attack target=bennett active=bennett;
actions+=attack target=fischl active=fischl;


'''