#title, author and description are mandatory fields
title = "Sample action list"
author = "genshinsim"
description = "This is a sample action list of just Ganyu spamming arrows."
tags = [
    "ganyu",
]

# version is an optional field for authors to keep track
version = "0.1.0"
# characters should be array of character names (all lowercase); this is mandatory
characters = [
    "ganyu",
]

# config is the action list, stored in multiline string
config = '''
target+="dummy" lvl=88 pyro=0.1 dendro=0.1 hydro=0.1 electro=0.1 geo=0.1 anemo=0.1 physical=.1 cryo=.1;
active+=ganyu;

actions+=skill target=ganyu;
actions+=burst target=ganyu;
actions+=aim target=ganyu;
'''